.TH "Projekt.Klasy.ZapisOdczytPliku.ZapisJSON" 3 "Sun Jan 13 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Projekt.Klasy.ZapisOdczytPliku.ZapisJSON
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZapisJSON\fP (List< Pogoda > doSerializacji)"
.br
.RI "Konstruktor wykorzystany do stworzenia całości zapisu "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file ZapisJSON\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Projekt\&.Klasy\&.ZapisOdczytPliku\&.ZapisJSON\&.ZapisJSON (List< Pogoda > doSerializacji)"

.PP
Konstruktor wykorzystany do stworzenia całości zapisu 
.PP
\fBParameters:\fP
.RS 4
\fIdoSerializacji\fP jest to lista obiektów typu Pogoda przesłana z obiektu, który zawiera listę wyświetloną w DataGrid
.RE
.PP

.PP
Definition at line 18 of file ZapisJSON\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
