.TH "Projekt.Klasy.WpisWindow.WpisWindowMetody" 3 "Sun Jan 13 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Projekt.Klasy.WpisWindow.WpisWindowMetody
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDodajModyfikacje\fP (List< Pogoda > doEdycji)"
.br
.ti -1c
.RI "void \fBWypelnijDanymi\fP (List< Pogoda > doEdycji, CheckBox DeszczCheckBox, CheckBox SniegCheckBox, CheckBox ZachmurzenieCheckBox, Calendar Kalendarz, TextBox CienienieTextBox, TextBox TemperaturaTextBox, Button DodajButton)"
.br
.ti -1c
.RI "void \fBDodajDoBazy\fP (List< Pogoda > doDodania)"
.br
.ti -1c
.RI "List< Pogoda > \fBBudujDodawanieParser\fP (int Id, CheckBox DeszczCheckBox, CheckBox SniegCheckBox, CheckBox ZachmurzenieCheckBox, string _miasto, Calendar Kalendarz, TextBox CienienieTextBox, TextBox TemperaturaTextBox)"
.br
.RI "Dodawanie do bazy, wszystko w try, więc zwraca błąd w messagebox jesli ktoś poda litery itp\&. "
.ti -1c
.RI "List< Pogoda > \fBBudujDodawanieParser\fP (CheckBox DeszczCheckBox, CheckBox SniegCheckBox, CheckBox ZachmurzenieCheckBox, string _miasto, Calendar Kalendarz, TextBox CienienieTextBox, TextBox TemperaturaTextBox)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file WpisWindowMetody\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "List<Pogoda> Projekt\&.Klasy\&.WpisWindow\&.WpisWindowMetody\&.BudujDodawanieParser (int Id, CheckBox DeszczCheckBox, CheckBox SniegCheckBox, CheckBox ZachmurzenieCheckBox, string _miasto, Calendar Kalendarz, TextBox CienienieTextBox, TextBox TemperaturaTextBox)"

.PP
Dodawanie do bazy, wszystko w try, więc zwraca błąd w messagebox jesli ktoś poda litery itp\&. 
.PP
\fBParameters:\fP
.RS 4
\fIDeszczCheckBox\fP 
.br
\fISniegCheckBox\fP 
.br
\fIZachmurzenieCheckBox\fP 
.br
\fI_miasto\fP 
.br
\fIKalendarz\fP 
.br
\fICienienieTextBox\fP 
.br
\fITemperaturaTextBox\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 71 of file WpisWindowMetody\&.cs\&.
.SS "List<Pogoda> Projekt\&.Klasy\&.WpisWindow\&.WpisWindowMetody\&.BudujDodawanieParser (CheckBox DeszczCheckBox, CheckBox SniegCheckBox, CheckBox ZachmurzenieCheckBox, string _miasto, Calendar Kalendarz, TextBox CienienieTextBox, TextBox TemperaturaTextBox)"

.PP
Definition at line 107 of file WpisWindowMetody\&.cs\&.
.SS "void Projekt\&.Klasy\&.WpisWindow\&.WpisWindowMetody\&.DodajDoBazy (List< Pogoda > doDodania)"

.PP
Definition at line 45 of file WpisWindowMetody\&.cs\&.
.SS "void Projekt\&.Klasy\&.WpisWindow\&.WpisWindowMetody\&.DodajModyfikacje (List< Pogoda > doEdycji)"

.PP
Definition at line 12 of file WpisWindowMetody\&.cs\&.
.SS "void Projekt\&.Klasy\&.WpisWindow\&.WpisWindowMetody\&.WypelnijDanymi (List< Pogoda > doEdycji, CheckBox DeszczCheckBox, CheckBox SniegCheckBox, CheckBox ZachmurzenieCheckBox, Calendar Kalendarz, TextBox CienienieTextBox, TextBox TemperaturaTextBox, Button DodajButton)"

.PP
Definition at line 32 of file WpisWindowMetody\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
