.TH "Projekt.Klasy.MainWindow.MainWindowMetody" 3 "Sun Jan 13 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Projekt.Klasy.MainWindow.MainWindowMetody
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWypelnijComboBox\fP (ComboBox combo)"
.br
.ti -1c
.RI "\fBMainWindowMetody\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file MainWindowMetody\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Projekt\&.Klasy\&.MainWindow\&.MainWindowMetody\&.MainWindowMetody ()"

.PP
Definition at line 41 of file MainWindowMetody\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Projekt\&.Klasy\&.MainWindow\&.MainWindowMetody\&.WypelnijComboBox (ComboBox combo)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIcombo\fP 
.RE
.PP

.PP
Definition at line 32 of file MainWindowMetody\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
