.TH "Projekt.Klasy" 3 "Sun Jan 13 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Projekt.Klasy
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMainWindow\fP"
.br
.ti -1c
.RI "namespace \fBPogodaWindow\fP"
.br
.ti -1c
.RI "namespace \fBWpisWindow\fP"
.br
.ti -1c
.RI "namespace \fBZapisOdczytPliku\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
