.TH "Projekt.Klasy.PogodaWindow.PogodaWindowMetody" 3 "Sun Jan 13 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Projekt.Klasy.PogodaWindow.PogodaWindowMetody
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPogodaWindowMetody\fP (string miasto)"
.br
.RI "knstruktor wykorzystany do pobrania szczegółów pogody w danej lokalizacji "
.ti -1c
.RI "void \fBWypelnijDataGrid\fP (DataGrid dataGrid)"
.br
.RI "metoda wypełniająca datagrid "
.ti -1c
.RI "List< Pogoda > \fBModyfikacja\fP (DataGrid grid)"
.br
.ti -1c
.RI "void \fBUsun\fP (List< Pogoda > modyfikacja, ref DataGrid grid)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< Pogoda > \fBszczegoly\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file PogodaWindowMetody\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Projekt\&.Klasy\&.PogodaWindow\&.PogodaWindowMetody\&.PogodaWindowMetody (string miasto)"

.PP
knstruktor wykorzystany do pobrania szczegółów pogody w danej lokalizacji 
.PP
\fBParameters:\fP
.RS 4
\fImiasto\fP 
.RE
.PP

.PP
Definition at line 18 of file PogodaWindowMetody\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "List<Pogoda> Projekt\&.Klasy\&.PogodaWindow\&.PogodaWindowMetody\&.Modyfikacja (DataGrid grid)"

.PP
Definition at line 56 of file PogodaWindowMetody\&.cs\&.
.SS "void Projekt\&.Klasy\&.PogodaWindow\&.PogodaWindowMetody\&.Usun (List< Pogoda > modyfikacja, ref DataGrid grid)"

.PP
Definition at line 75 of file PogodaWindowMetody\&.cs\&.
.SS "void Projekt\&.Klasy\&.PogodaWindow\&.PogodaWindowMetody\&.WypelnijDataGrid (DataGrid dataGrid)"

.PP
metoda wypełniająca datagrid 
.PP
\fBParameters:\fP
.RS 4
\fIdataGrid\fP DataGrid do wypełnienia
.RE
.PP

.PP
Definition at line 51 of file PogodaWindowMetody\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<Pogoda> Projekt\&.Klasy\&.PogodaWindow\&.PogodaWindowMetody\&.szczegoly"

.PP
Definition at line 12 of file PogodaWindowMetody\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
