.TH "PogodaWindow/ZapisJSON.cs" 3 "Sun Jan 13 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PogodaWindow/ZapisJSON.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProjekt\&.Klasy\&.ZapisOdczytPliku\&.ZapisJSON\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBProjekt\fP"
.br
.ti -1c
.RI "namespace \fBProjekt\&.Klasy\fP"
.br
.ti -1c
.RI "namespace \fBProjekt\&.Klasy\&.ZapisOdczytPliku\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
