//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Baza
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Klasa dla wpisu z bazy danych.
    /// </summary>
    /// <seealso cref="Projekt.WpisBazaDanych" />
    public partial class Pogoda : WpisBazaDanych
    {
        public string Miasto { get; set; }
        public Nullable<int> Temperatura { get; set; }
        public string Ciśnienie { get; set; }
        public Nullable<bool> Zachmurzenie { get; set; }
        public Nullable<bool> Deszcz { get; set; }
        public Nullable<bool> Śnieg { get; set; }
    }
}
